### ISSUE TITLE
Publish Document Model Editor Storybook addon

### ISSUE THREAD

**Issue by acaldas** [powerhouse-inc/document-model-boilerplate#4]

**Comment by CallmeT-ty** [comment]
@ryanwolhuter Is this one done? Ty!!

**Comment by ryanwolhuter** [comment]
> @ryanwolhuter Is this one done? Ty!!

there's no description here so I'm not 100% sure if what I did is the same as this, but I can confirm that publishing the storybook for this repo to chromatic is done and working 👍
